### ISSUE TITLE
Feature Vector is not written

### ISSUE THREAD

**Issue by haritha91** [delange/image2image#1]
Tried the code. Though the file paths are correctly set, the feature vector is not created. it throws an warning saying
`WARNING: There are no rows in the DataSet being written.
Elapsed time: 00:00:22.2248954
Finished writing 0 rows.
Writing completed.`

**Comment by revodavid** [comment]
The issue is with the creation of the "images" vector, which is pointing to the wrong folder. It should be:

```r
images <- list.files(paste0(imageLocation,"collection"), recursive = TRUE, pattern = "\\.jpg",  full.names=TRUE)
```

**Comment by haritha91** [comment]
This works fine now. Thanks a lot
